import turtle
import time
from turtle import *
from vlc import vlc
import sys

def bonhomme_1(erreur):
  """"La fonction bonhomme prend en argument la variable erreur et dessine, à chaque erreur ajoutée, une partie du bonhomme"""
  if erreur==1:
    turtle.pu()
    turtle.goto(-760,-120)
    turtle.pd()
    turtle.forward(200)
    turtle.pu()
    turtle.backward(100)
    turtle.pd()
  elif erreur==2:
    pu()
    goto(-660,-120)
    pd()
    turtle.left(90)
    turtle.forward(250)
  elif erreur==3:
    pu()
    goto(-660,130)
    pd()
    turtle.right(90)
    turtle.forward(150)
  elif erreur==4:
    pu()
    goto(-505,130)
    pd()
    turtle.right(90)
    turtle.forward(40)
  elif erreur==5:
    pu()
    goto(-520,72)
    pd()
    turtle.pu()
    turtle.forward(30)
    turtle.left(90)
    turtle.forward(15)
    turtle.pd()
    turtle.circle(25)
  elif erreur==6:
    pu()
    goto(-505,45)
    pd()
    turtle.right(90)
    turtle.forward(35)
  elif erreur==7:
    pu()
    goto(-505,5)
    pd()
    turtle.left(90)
    turtle.forward(30)
    turtle.backward(30)
  elif erreur==8:
    pu()
    goto(-505,5)
    pd()
    turtle.backward(30)
    turtle.forward(30)
  elif erreur==9:
    pu()
    goto(-505,7)
    pd()
    turtle.right(90)
    turtle.forward(20)
  elif erreur==10:
    pu()
    goto(-505,-15)
    pd()
    turtle.right(45)
    turtle.forward(30)
    turtle.backward(30)
  elif erreur==11:
    pu()
    goto(-505,-15)
    pd()
    turtle.left(90)
    turtle.forward(30)
    turtle.backward(30)
    time.sleep(2)
    turtle.clear()
    pu()
    goto(0,0)
    pd()
    player = vlc.MediaPlayer("sounds\game_over.wav")
    player.play()
    turtle.write("GAME OVER", align="center",font=("Times", 35, "normal"))
    time.sleep(10) 
    sys.exit()

def bonhomme_2(erreur):
  if erreur==1:
    turtle.pu()
    turtle.goto(-760,-120)
    turtle.pd()
    turtle.forward(200)
    turtle.pu()
    turtle.backward(100)
    turtle.pd()
    turtle.left(90)
    turtle.forward(250)
  elif erreur==2:
    pu()
    goto(-660,130)
    pd()
    turtle.right(90)
    turtle.forward(150)
  elif erreur==3:
    pu()
    goto(-505,130)
    pd()
    turtle.right(90)
    turtle.forward(40)
  elif erreur==4:
    pu()
    goto(-520,72)
    pd()
    turtle.pu()
    turtle.forward(30)
    turtle.left(90)
    turtle.forward(15)
    turtle.pd()
    turtle.circle(25)
  elif erreur==5:
    pu()
    goto(-505,45)
    pd()
    turtle.right(90)
    turtle.forward(30)
  elif erreur==6:
    pu()
    goto(-505,5)
    pd()
    turtle.left(90)
    turtle.forward(30)
    turtle.backward(30)
    turtle.backward(30)
    turtle.forward(30)
  elif erreur==7:
    pu()
    goto(-505,7)
    pd()
    turtle.right(90)
    turtle.forward(20)
    turtle.right(45)
    turtle.forward(30)
    turtle.backward(30)
  elif erreur==8:
    pu()
    goto(-505,-15)
    pd()
    turtle.left(90)
    turtle.forward(30)
    turtle.backward(30)
    time.sleep(2)
    turtle.clear()
    pu()
    goto(0,0)
    pd()
    player = vlc.MediaPlayer("sounds\game_over.wav")
    player.play()
    turtle.write("GAME OVER", align="center",font=("Times", 35, "normal"))
    time.sleep(10) 
    sys.exit()

def bonhomme_3(erreur):
  if erreur==1:
    turtle.pu()
    turtle.goto(-760,-120)
    turtle.pd()
    turtle.forward(200)
    turtle.pu()
    turtle.backward(100)
    turtle.pd()
    turtle.left(90)
    turtle.forward(250)
  elif erreur==2:
    pu()
    goto(-660,130)
    pd()
    turtle.right(90)
    turtle.forward(150)
    turtle.right(90)
    turtle.forward(40)
  elif erreur==3:
    pu()
    goto(-520,72)
    pd()
    turtle.pu()
    turtle.forward(30)
    turtle.left(90)
    turtle.forward(15)
    turtle.pd()
    turtle.circle(25)
    turtle.right(90)
    turtle.forward(35)
  elif erreur==4:
    pu()
    goto(-505,5)
    pd()
    turtle.left(90)
    turtle.forward(30)
    turtle.backward(30)
    turtle.backward(30)
    turtle.forward(30)
  elif erreur==5:
    pu()
    goto(-505,7)
    pd()
    turtle.right(90)
    turtle.forward(20)
    turtle.right(45)
    turtle.forward(30)
    turtle.backward(30)
    turtle.left(90)
    turtle.forward(30)
    turtle.backward(30)
    time.sleep(2)
    turtle.clear()
    pu()
    goto(0,0)
    pd()
    player = vlc.MediaPlayer("sounds\game_over.wav")
    player.play()
    turtle.write("GAME OVER", align="center",font=("Times", 35, "normal"))
    time.sleep(10) 
    sys.exit()

def winning(lettre_vrai, mot):
    
    player = vlc.MediaPlayer("sounds\music-background.wav")
    if lettre_vrai==len(mot):

        time.sleep(1)
        turtle.clear()
        turtle.write("YOU WON !", align="center",font=("Times", 50, "normal"))
        player.stop
        player = vlc.MediaPlayer("sounds\win.wav")
        player.play()
        time.sleep(10) 
        sys.exit() #On arrête tout le programme